// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgLV6xo0wn2HUNaduG31CxMNwR7BJUdvw',
    appId: '1:1011924739423:web:5ca25ba106383e955a42ea',
    messagingSenderId: '1011924739423',
    projectId: 'ecoride-82bb2',
    authDomain: 'ecoride-82bb2.firebaseapp.com',
    storageBucket: 'ecoride-82bb2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALum6VuO2KC31Mvd1IXA1TfuukaaAjiKY',
    appId: '1:1011924739423:android:2099ad417aac6e0e5a42ea',
    messagingSenderId: '1011924739423',
    projectId: 'ecoride-82bb2',
    storageBucket: 'ecoride-82bb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQoiI7wR7JN8MfR1uFCDY8B3d5y5E_DB8',
    appId: '1:1011924739423:ios:e9ecf22585b701585a42ea',
    messagingSenderId: '1011924739423',
    projectId: 'ecoride-82bb2',
    storageBucket: 'ecoride-82bb2.firebasestorage.app',
    iosBundleId: 'com.example.ecoride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQoiI7wR7JN8MfR1uFCDY8B3d5y5E_DB8',
    appId: '1:1011924739423:ios:e9ecf22585b701585a42ea',
    messagingSenderId: '1011924739423',
    projectId: 'ecoride-82bb2',
    storageBucket: 'ecoride-82bb2.firebasestorage.app',
    iosBundleId: 'com.example.ecoride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgLV6xo0wn2HUNaduG31CxMNwR7BJUdvw',
    appId: '1:1011924739423:web:92d2cd244b5813c85a42ea',
    messagingSenderId: '1011924739423',
    projectId: 'ecoride-82bb2',
    authDomain: 'ecoride-82bb2.firebaseapp.com',
    storageBucket: 'ecoride-82bb2.firebasestorage.app',
  );
}
